services:
  - type: web
    name: perfume-backend
    env: python
    pythonVersion: 3.11.9   
    buildCommand: "./build.sh"
    startCommand: "gunicorn backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        value: your-secret-key
      - key: DATABASE_URL
        value: your-database-url
